name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install databricks-cli

      - name: Run tests/Set PYTHONPATH
        run: echo "PYTHONPATH=." >> $GITHUB_ENV

      - name: Configure Databricks CLI
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks configure --token <<EOF
          $DATABRICKS_HOST token
          $DATABRICKS_TOKEN
          EOF

      # Supprimer le répertoire Databricks avant l'importation pour éviter les conflits
      - name: Remove Existing Databricks Directory
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks workspace rm -r /Repos/CI-CD_test/Projet_Databricks_CI-CD/notebooks || true

      - name: Upload Notebooks to Databricks
        run: |
          databricks workspace import_dir notebooks /Repos/CI-CD_test/Projet_Databricks_CI-CD/notebooks 

      - name: Trigger Databricks Job
        run: |
          databricks jobs run-now --job-id 832710156431865